### ISSUE TITLE
Problem running with Processing 2.2.1

### ISSUE THREAD

**Issue by VladimirCores** [cacheflowe/haxademic#6]
Actually latest version of processing that i find is 2.2.1 from official site 
https://processing.org/download/?processing

And with all library connected i get this list of errors, there is many

![image](https://cloud.githubusercontent.com/assets/442111/11320821/10f34018-90b8-11e5-96c8-24701796e446.png)

![image](https://cloud.githubusercontent.com/assets/442111/11320836/5abcf590-90b8-11e5-8af1-f50eb5524727.png)

I connect all library from lib folder to the project.
I run Win7 OS, and Java 1.6.
I suppose it's because of newer version of Processing.
Please help figure out how to solve that problem.

**Comment by cacheflowe** [comment]
I'm guessing there might be some additional libraries that you haven't connected. Honestly this repository isn't quite ready and tested for people to download and start using. It's maybe better to use as example code. I do think that Application class in your screenshot might not work on Windows.

**Comment by cacheflowe** [comment]
@DQvsRA I'm also thinking you should try running this in Eclipse, instead of FlashBuilder. That's probably the reason it can't resolve the Java library paths.
